---
AWSTemplateFormatVersion: '2010-09-09'

Globals:
  Api:
    MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        MetricsEnabled: true
        ResourcePath: /*

  Function:
    Handler: main
    Runtime: go1.x
    Timeout: 5
    Tracing: Active

Parameters:
  SlackToken:
    Default: "Slack token not set"
    Description: "Slack token"
    Type: String
  SlackSigningSecret:
    Default: "Slack signing secret not set"
    Description: "Slack signing secret"
    Type: String
  DynamoDbEndpoint:
    Default: ""
    Description: "Dynamo DB endpoint"
    Type: String

Resources:
  DashboardFunction:
    Properties:
      CodeUri: ./handlers/dashboard
      Events:
        Request:
          Properties:
            Method: GET
            Path: /
          Type: Api
      FunctionName: !Sub ${AWS::StackName}-DashboardFunction
      Handler: main
      Runtime: go1.x
    Type: AWS::Serverless::Function

  SlashFunction:
    Properties:
      CodeUri: ./handlers/slash
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
      Events:
        Request:
          Properties:
            Method: POST
            Path: /slash
          Type: Api
      FunctionName: !Sub ${AWS::StackName}-SlashFunction
      Handler: main
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref bZappTable
      Runtime: go1.x
    Type: AWS::Serverless::Function

  InteractionFunction:
    Properties:
      CodeUri: ./handlers/interaction
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
          DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
      Events:
        Request:
          Properties:
            Method: POST
            Path: /interaction
          Type: Api
      FunctionName: !Sub ${AWS::StackName}-InteractionFunction
      Handler: main
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref bZappTable
      Runtime: go1.x
    Type: AWS::Serverless::Function

  bZappTable:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: bZappTable
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Type: AWS::Serverless::SimpleTable

Transform: AWS::Serverless-2016-10-31
